#!/usr/bin/env python3
"""One-time cleanup of phantom artists in a Navidrome database.

Navidrome creates artist rows for every credit it finds in the tags —
including songwriter/producer/featured credits (roles like composer, writer,
performer, etc.). With fnack's tag stripping (v0.2.34+) new downloads no
longer carry those credits, but the already-created artist rows persist.

This script:
  1. deletes `media_file_artists` rows whose role is not artist/albumartist
     (Navidrome regenerates them from tags on the next scan), and
  2. deletes `artist` rows that have no primary media files and no albums —
     i.e. pure phantom credits.

Run AFTER fnack has re-tagged the library (the boot maintenance pass strips
the credit tags), then trigger a Navidrome FULL rescan so the scanner
rebuilds participants from the now-clean tags.

Usage:
    python3 scripts/clean_navidrome_artists.py /path/to/navidrome.db
"""

import sqlite3
import sys


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    db_path = sys.argv[1]

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()

    # ---- schema guards ----------------------------------------------------
    mfa_cols = {r[1] for r in cur.execute("PRAGMA table_info(media_file_artists)")}
    art_cols = {r[1] for r in cur.execute("PRAGMA table_info(artist)")}
    if not ({"media_file_id", "artist_id", "role"} <= mfa_cols and {"id"} <= art_cols):
        print("ERROR: unexpected Navidrome schema. Refusing to touch it.")
        return 1

    # 1. drop non-artist-role participant rows (regenerated by the scanner)
    cur.execute(
        "DELETE FROM media_file_artists WHERE role NOT IN ('artist', 'albumartist', '')"
    )
    removed_participants = cur.rowcount

    # 2. delete artist rows with no primary media files and no albums
    cur.execute(
        """
        DELETE FROM artist WHERE id IN (
          SELECT ar.id FROM artist ar
          WHERE NOT EXISTS (SELECT 1 FROM media_file mf WHERE mf.artist_id = ar.id)
            AND NOT EXISTS (SELECT 1 FROM album a WHERE a.album_artist_id = ar.id)
        )
        """
    )
    removed_artists = cur.rowcount

    # Rebuild the artist full-text index
    try:
        cur.execute("INSERT INTO artist_fts(artist_fts) VALUES('rebuild')")
    except Exception:
        pass  # some schemas rebuild FTS on the next scan

    conn.commit()
    conn.close()
    print(
        f"Done: removed {removed_participants} non-artist participant row(s), "
        f"{removed_artists} phantom artist row(s)."
    )
    print("Start Navidrome and trigger a FULL library rescan to rebuild participants from tags.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
